#!/bin/sh
url="https://raw.githubusercontent.com/Smeueg/Dotfiles/master/.local/bin/smeuesic"
if [ "$(command -v wget)" ]; then eval "$(wget -qO- "${url}")"
elif [ "$(command -v curl)" ]; then eval "$(curl -sL "${url}")"
else printf '\033[1m\033[31m[ERROR]\033[0m `wget` and `curl` is not installed. One of them must be installed to use this script\n'
fi
